# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'buyerUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 601)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.commodityTable = QtWidgets.QTableWidget(self.centralwidget)
        self.commodityTable.setGeometry(QtCore.QRect(10, 90, 781, 211))
        self.commodityTable.setObjectName("commodityTable")
        self.commodityTable.setColumnCount(0)
        self.commodityTable.setRowCount(0)
        self.usernoLabel = QtWidgets.QLabel(self.centralwidget)
        self.usernoLabel.setGeometry(QtCore.QRect(70, 20, 72, 15))
        self.usernoLabel.setObjectName("usernoLabel")
        self.InfousernoLabel = QtWidgets.QLabel(self.centralwidget)
        self.InfousernoLabel.setGeometry(QtCore.QRect(150, 20, 101, 16))
        self.InfousernoLabel.setText("")
        self.InfousernoLabel.setObjectName("InfousernoLabel")
        self.nameLabel = QtWidgets.QLabel(self.centralwidget)
        self.nameLabel.setGeometry(QtCore.QRect(310, 20, 72, 15))
        self.nameLabel.setObjectName("nameLabel")
        self.InfonameLabel = QtWidgets.QLabel(self.centralwidget)
        self.InfonameLabel.setGeometry(QtCore.QRect(390, 20, 91, 16))
        self.InfonameLabel.setText("")
        self.InfonameLabel.setObjectName("InfonameLabel")
        self.sexLabel = QtWidgets.QLabel(self.centralwidget)
        self.sexLabel.setGeometry(QtCore.QRect(550, 20, 72, 15))
        self.sexLabel.setObjectName("sexLabel")
        self.InfosexLabel = QtWidgets.QLabel(self.centralwidget)
        self.InfosexLabel.setGeometry(QtCore.QRect(630, 20, 72, 15))
        self.InfosexLabel.setText("")
        self.InfosexLabel.setObjectName("InfosexLabel")
        self.telLabel = QtWidgets.QLabel(self.centralwidget)
        self.telLabel.setGeometry(QtCore.QRect(70, 60, 72, 15))
        self.telLabel.setObjectName("telLabel")
        self.InfotelLabel = QtWidgets.QLabel(self.centralwidget)
        self.InfotelLabel.setGeometry(QtCore.QRect(140, 60, 151, 16))
        self.InfotelLabel.setText("")
        self.InfotelLabel.setObjectName("InfotelLabel")
        self.repLabel = QtWidgets.QLabel(self.centralwidget)
        self.repLabel.setGeometry(QtCore.QRect(310, 60, 72, 15))
        self.repLabel.setObjectName("repLabel")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 310, 781, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.showcartButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.showcartButton.setObjectName("showcartButton")
        self.horizontalLayout.addWidget(self.showcartButton)
        self.selectLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.selectLabel.setObjectName("selectLabel")
        self.horizontalLayout.addWidget(self.selectLabel)
        self.selectLine = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.selectLine.setObjectName("selectLine")
        self.horizontalLayout.addWidget(self.selectLine)
        self.cartnumLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.cartnumLabel.setObjectName("cartnumLabel")
        self.horizontalLayout.addWidget(self.cartnumLabel)
        self.cartnumLine = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.cartnumLine.setObjectName("cartnumLine")
        self.horizontalLayout.addWidget(self.cartnumLine)
        self.addButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.addButton.setObjectName("addButton")
        self.horizontalLayout.addWidget(self.addButton)
        self.deleteButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.deleteButton.setObjectName("deleteButton")
        self.horizontalLayout.addWidget(self.deleteButton)
        self.updateButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.updateButton.setObjectName("updateButton")
        self.horizontalLayout.addWidget(self.updateButton)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 370, 781, 192))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        # MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        # MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.usernoLabel.setText(_translate("MainWindow", "用户编号"))
        self.nameLabel.setText(_translate("MainWindow", "用户姓名"))
        self.sexLabel.setText(_translate("MainWindow", "用户性别"))
        self.telLabel.setText(_translate("MainWindow", "联系电话"))
        self.repLabel.setText(_translate("MainWindow", "信誉度"))
        self.showcartButton.setText(_translate("MainWindow", "查看购物车"))
        self.selectLabel.setText(_translate("MainWindow", "商品编号"))
        self.cartnumLabel.setText(_translate("MainWindow", "商品数目"))
        self.addButton.setText(_translate("MainWindow", "加入商品"))
        self.deleteButton.setText(_translate("MainWindow", "删除商品"))
        self.updateButton.setText(_translate("MainWindow", "更新购物车"))
