# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sellerUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(944, 811)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.usernolabel = QtWidgets.QLabel(self.centralwidget)
        self.usernolabel.setGeometry(QtCore.QRect(140, 30, 72, 15))
        self.usernolabel.setObjectName("usernolabel")
        self.Infousernolabel = QtWidgets.QLabel(self.centralwidget)
        self.Infousernolabel.setGeometry(QtCore.QRect(220, 30, 72, 15))
        self.Infousernolabel.setText("")
        self.Infousernolabel.setObjectName("Infousernolabel")
        self.namelabel = QtWidgets.QLabel(self.centralwidget)
        self.namelabel.setGeometry(QtCore.QRect(380, 30, 72, 15))
        self.namelabel.setObjectName("namelabel")
        self.Infonamelabel = QtWidgets.QLabel(self.centralwidget)
        self.Infonamelabel.setGeometry(QtCore.QRect(460, 30, 72, 15))
        self.Infonamelabel.setText("")
        self.Infonamelabel.setObjectName("Infonamelabel")
        self.sexlabel = QtWidgets.QLabel(self.centralwidget)
        self.sexlabel.setGeometry(QtCore.QRect(630, 30, 72, 15))
        self.sexlabel.setObjectName("sexlabel")
        self.Infosexlabel = QtWidgets.QLabel(self.centralwidget)
        self.Infosexlabel.setGeometry(QtCore.QRect(710, 30, 72, 15))
        self.Infosexlabel.setText("")
        self.Infosexlabel.setObjectName("Infosexlabel")
        self.tellabel = QtWidgets.QLabel(self.centralwidget)
        self.tellabel.setGeometry(QtCore.QRect(140, 70, 72, 15))
        self.tellabel.setObjectName("tellabel")
        self.Infotellabel = QtWidgets.QLabel(self.centralwidget)
        self.Infotellabel.setGeometry(QtCore.QRect(210, 70, 72, 15))
        self.Infotellabel.setText("")
        self.Infotellabel.setObjectName("Infotellabel")
        self.shopnolabel = QtWidgets.QLabel(self.centralwidget)
        self.shopnolabel.setGeometry(QtCore.QRect(380, 70, 131, 16))
        self.shopnolabel.setObjectName("shopnolabel")
        self.Infoshopnolabel = QtWidgets.QLabel(self.centralwidget)
        self.Infoshopnolabel.setGeometry(QtCore.QRect(520, 70, 72, 15))
        self.Infoshopnolabel.setText("")
        self.Infoshopnolabel.setObjectName("Infoshopnolabel")
        self.commodityTable = QtWidgets.QTableWidget(self.centralwidget)
        self.commodityTable.setGeometry(QtCore.QRect(20, 190, 901, 221))
        self.commodityTable.setObjectName("commodityTable")
        self.commodityTable.setColumnCount(0)
        self.commodityTable.setRowCount(0)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 100, 901, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comnocheckBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.comnocheckBox.setObjectName("comnocheckBox")
        self.horizontalLayout.addWidget(self.comnocheckBox)
        self.comnoLine = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.comnoLine.setObjectName("comnoLine")
        self.horizontalLayout.addWidget(self.comnoLine)
        self.comnamecheckBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.comnamecheckBox.setObjectName("comnamecheckBox")
        self.horizontalLayout.addWidget(self.comnamecheckBox)
        self.comnameLine = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.comnameLine.setObjectName("comnameLine")
        self.horizontalLayout.addWidget(self.comnameLine)
        self.pricecheckBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.pricecheckBox.setObjectName("pricecheckBox")
        self.horizontalLayout.addWidget(self.pricecheckBox)
        self.priceLine = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.priceLine.setObjectName("priceLine")
        self.horizontalLayout.addWidget(self.priceLine)
        self.offcheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.offcheckBox.setGeometry(QtCore.QRect(20, 150, 91, 19))
        self.offcheckBox.setObjectName("offcheckBox")
        self.offLine = QtWidgets.QLineEdit(self.centralwidget)
        self.offLine.setGeometry(QtCore.QRect(90, 150, 111, 21))
        self.offLine.setObjectName("offLine")
        self.textcheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.textcheckBox.setGeometry(QtCore.QRect(220, 150, 91, 19))
        self.textcheckBox.setObjectName("textcheckBox")
        self.textLine = QtWidgets.QLineEdit(self.centralwidget)
        self.textLine.setGeometry(QtCore.QRect(290, 150, 441, 21))
        self.textLine.setObjectName("textLine")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 420, 901, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.addcomButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.addcomButton.setObjectName("addcomButton")
        self.horizontalLayout_2.addWidget(self.addcomButton)
        self.deletecomButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.deletecomButton.setObjectName("deletecomButton")
        self.horizontalLayout_2.addWidget(self.deletecomButton)
        self.updatecomButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.updatecomButton.setObjectName("updatecomButton")
        self.horizontalLayout_2.addWidget(self.updatecomButton)
        self.selectcomButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.selectcomButton.setObjectName("selectcomButton")
        self.horizontalLayout_2.addWidget(self.selectcomButton)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(20, 480, 901, 51))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ordernocheckBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget_3)
        self.ordernocheckBox.setObjectName("ordernocheckBox")
        self.horizontalLayout_3.addWidget(self.ordernocheckBox)
        self.ordernoLine = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.ordernoLine.setObjectName("ordernoLine")
        self.horizontalLayout_3.addWidget(self.ordernoLine)
        self.buyernocheckBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget_3)
        self.buyernocheckBox.setObjectName("buyernocheckBox")
        self.horizontalLayout_3.addWidget(self.buyernocheckBox)
        self.buyernoLine = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.buyernoLine.setObjectName("buyernoLine")
        self.horizontalLayout_3.addWidget(self.buyernoLine)
        self.cnamecheckBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget_3)
        self.cnamecheckBox.setObjectName("cnamecheckBox")
        self.horizontalLayout_3.addWidget(self.cnamecheckBox)
        self.cnameLine = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.cnameLine.setObjectName("cnameLine")
        self.horizontalLayout_3.addWidget(self.cnameLine)
        self.ordernumcheckBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget_3)
        self.ordernumcheckBox.setObjectName("ordernumcheckBox")
        self.horizontalLayout_3.addWidget(self.ordernumcheckBox)
        self.ordernumLine = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.ordernumLine.setObjectName("ordernumLine")
        self.horizontalLayout_3.addWidget(self.ordernumLine)
        self.orderTable = QtWidgets.QTableWidget(self.centralwidget)
        self.orderTable.setGeometry(QtCore.QRect(20, 540, 901, 192))
        self.orderTable.setObjectName("orderTable")
        self.orderTable.setColumnCount(0)
        self.orderTable.setRowCount(0)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(20, 740, 901, 41))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.addorderButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.addorderButton.setObjectName("addorderButton")
        self.horizontalLayout_4.addWidget(self.addorderButton)
        self.deleteorderButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.deleteorderButton.setObjectName("deleteorderButton")
        self.horizontalLayout_4.addWidget(self.deleteorderButton)
        self.updateorderButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.updateorderButton.setObjectName("updateorderButton")
        self.horizontalLayout_4.addWidget(self.updateorderButton)
        self.selectorderButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.selectorderButton.setObjectName("selectorderButton")
        self.horizontalLayout_4.addWidget(self.selectorderButton)
        # MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        # MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.usernolabel.setText(_translate("MainWindow", "用户编号"))
        self.namelabel.setText(_translate("MainWindow", "用户姓名"))
        self.sexlabel.setText(_translate("MainWindow", "用户性别"))
        self.tellabel.setText(_translate("MainWindow", "联系方式"))
        self.shopnolabel.setText(_translate("MainWindow", "所管理的商店编号"))
        self.comnocheckBox.setText(_translate("MainWindow", "商品编号"))
        self.comnamecheckBox.setText(_translate("MainWindow", "商品名称"))
        self.pricecheckBox.setText(_translate("MainWindow", "价格"))
        self.offcheckBox.setText(_translate("MainWindow", "折扣"))
        self.textcheckBox.setText(_translate("MainWindow", "描述"))
        self.addcomButton.setText(_translate("MainWindow", "增加商品"))
        self.deletecomButton.setText(_translate("MainWindow", "删除商品"))
        self.updatecomButton.setText(_translate("MainWindow", "修改商品参数"))
        self.selectcomButton.setText(_translate("MainWindow", "查找商品"))
        self.ordernocheckBox.setText(_translate("MainWindow", "订单编号"))
        self.buyernocheckBox.setText(_translate("MainWindow", "买家编号"))
        self.cnamecheckBox.setText(_translate("MainWindow", "商品名称"))
        self.ordernumcheckBox.setText(_translate("MainWindow", "商品数量"))
        self.addorderButton.setText(_translate("MainWindow", "添加订单"))
        self.deleteorderButton.setText(_translate("MainWindow", "删除订单"))
        self.updateorderButton.setText(_translate("MainWindow", "修改订单"))
        self.selectorderButton.setText(_translate("MainWindow", "查找订单"))
