# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lab2demo.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 520, 781, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.Function_horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.Function_horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.Function_horizontalLayout.setObjectName("Function_horizontalLayout")
        self.selectButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.selectButton.setObjectName("selectButton")
        self.Function_horizontalLayout.addWidget(self.selectButton)
        self.insertButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.insertButton.setObjectName("insertButton")
        self.Function_horizontalLayout.addWidget(self.insertButton)
        self.deleteButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.deleteButton.setObjectName("deleteButton")
        self.Function_horizontalLayout.addWidget(self.deleteButton)
        self.updateButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.updateButton.setObjectName("updateButton")
        self.Function_horizontalLayout.addWidget(self.updateButton)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 270, 781, 241))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.connectButton = QtWidgets.QPushButton(self.centralwidget)
        self.connectButton.setGeometry(QtCore.QRect(10, 10, 93, 28))
        self.connectButton.setObjectName("connectButton")
        self.closeButton = QtWidgets.QPushButton(self.centralwidget)
        self.closeButton.setGeometry(QtCore.QRect(700, 10, 93, 28))
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(110, 50, 231, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.ename_horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.ename_horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.ename_horizontalLayout.setObjectName("ename_horizontalLayout")
        self.enamecheckBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
        self.enamecheckBox.setObjectName("enamecheckBox")
        self.ename_horizontalLayout.addWidget(self.enamecheckBox)
        self.enamelineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.enamelineEdit.setObjectName("enamelineEdit")
        self.ename_horizontalLayout.addWidget(self.enamelineEdit)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(450, 50, 231, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.essn_horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.essn_horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.essn_horizontalLayout.setObjectName("essn_horizontalLayout")
        self.essncheckBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget_3)
        self.essncheckBox.setObjectName("essncheckBox")
        self.essn_horizontalLayout.addWidget(self.essncheckBox)
        self.essnlineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.essnlineEdit.setObjectName("essnlineEdit")
        self.essn_horizontalLayout.addWidget(self.essnlineEdit)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(110, 90, 231, 41))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.address_horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.address_horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.address_horizontalLayout.setObjectName("address_horizontalLayout")
        self.addresscheckBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget_4)
        self.addresscheckBox.setObjectName("addresscheckBox")
        self.address_horizontalLayout.addWidget(self.addresscheckBox)
        self.addresslineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        self.addresslineEdit.setObjectName("addresslineEdit")
        self.address_horizontalLayout.addWidget(self.addresslineEdit)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(110, 130, 231, 41))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.superssn_horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.superssn_horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.superssn_horizontalLayout.setObjectName("superssn_horizontalLayout")
        self.superssncheckBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget_5)
        self.superssncheckBox.setObjectName("superssncheckBox")
        self.superssn_horizontalLayout.addWidget(self.superssncheckBox)
        self.superssnlineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_5)
        self.superssnlineEdit.setObjectName("superssnlineEdit")
        self.superssn_horizontalLayout.addWidget(self.superssnlineEdit)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(450, 90, 231, 41))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.salary_horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.salary_horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.salary_horizontalLayout.setObjectName("salary_horizontalLayout")
        self.salarycheckBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget_6)
        self.salarycheckBox.setObjectName("salarycheckBox")
        self.salary_horizontalLayout.addWidget(self.salarycheckBox)
        self.salarylineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_6)
        self.salarylineEdit.setObjectName("salarylineEdit")
        self.salary_horizontalLayout.addWidget(self.salarylineEdit)
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(450, 130, 231, 41))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.dno_horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.dno_horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.dno_horizontalLayout.setObjectName("dno_horizontalLayout")
        self.dnocheckBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget_7)
        self.dnocheckBox.setObjectName("dnocheckBox")
        self.dno_horizontalLayout.addWidget(self.dnocheckBox)
        self.dnolineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_7)
        self.dnolineEdit.setObjectName("dnolineEdit")
        self.dno_horizontalLayout.addWidget(self.dnolineEdit)
        self.clearButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearButton.setGeometry(QtCore.QRect(700, 170, 93, 28))
        self.clearButton.setObjectName("clearButton")
        self.sqltextBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.sqltextBrowser.setGeometry(QtCore.QRect(10, 210, 781, 51))
        self.sqltextBrowser.setObjectName("sqltextBrowser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.selectButton.setText(_translate("MainWindow", "查询记录"))
        self.insertButton.setText(_translate("MainWindow", "添加记录"))
        self.deleteButton.setText(_translate("MainWindow", "删除记录"))
        self.updateButton.setText(_translate("MainWindow", "更新记录"))
        self.connectButton.setText(_translate("MainWindow", "连接数据库"))
        self.closeButton.setText(_translate("MainWindow", "断开连接"))
        self.enamecheckBox.setText(_translate("MainWindow", "员工名字"))
        self.essncheckBox.setText(_translate("MainWindow", "员工编号"))
        self.addresscheckBox.setText(_translate("MainWindow", "居住住址"))
        self.superssncheckBox.setText(_translate("MainWindow", "直接领导编号"))
        self.salarycheckBox.setText(_translate("MainWindow", "员工工资"))
        self.dnocheckBox.setText(_translate("MainWindow", "所属部门"))
        self.clearButton.setText(_translate("MainWindow", "清除表单"))
